const screenName = {
    SPLASH_SCREEN: 'SPLASH_SCREEN',
    AUTH_SCREEN: 'AUTH_SCREEN',
    HOME_SCREEN: 'HOME_SCREEN',
    MAIN_TAB: 'MAIN_TAB',
    SEARCH_SCREEN: 'SEARCH_SCREEN',
    MY_PROFILE_SCREEN: 'MY_PROFILE_SCREEN',
    LOGIN_SCREEN: 'LOGIN_SCREEN',
    SIGNUP_SCREEN: 'SIGNUP_SCREEN',
    USER_PROFILE_SCREEN: 'USER_PROFILE_SCREEN',
    RECIPE_FEED_SCREEN: 'RECIPE_FEED_SCREEN',
};

export default screenName